### ISSUE TITLE
No-exception routines

### ISSUE THREAD

**Issue by egorpugin** [GiovanniDicanio/WinReg#18]
Hi,

Is it possible to add support for not throwing exceptions?
So, functions will return bool.

**Comment by GiovanniDicanio** [comment]
I'm not going to add this kind of non-throwing methods to the current code base. I made a design choice of returning the "natural" expected value (like a `DWORD` or a `std::wstring`), and throwing exceptions on errors:

```
DWORD GetDwordValue(const std::wstring& valueName) const;
std::wstring GetStringValue(const std::wstring& valueName) const;
```

Returning a `bool` would mean using a style like that:

```
bool GetDwordValue(DWORD& result, const std::wstring& valueName) const;
bool GetStringValue(std::wstring& result, const std::wstring& valueName) const;
```

which I'm not going to adopt for this code base.

In addition, in such case, I would prefer returning a `HRESULT` instead of a `bool`, as the former carries more meaningful error information than just success/fail (`true`/`false`).

Note also that, even if you adopt an error-returning style, you **can't** mark the methods as `noexcept`, because even a `std::wstring` or a `std::vector<std::wstring>` allocation may throw an exception.

So, of course you are free to fork this code and _"add support for not throwing exceptions"_, but I'm not going to do it here.

**Comment by egorpugin** [comment]
1) I do not mean `noexcept` kw, but indicate error as false, for example.
2) With C++17 it is possible to return: `std::optional<std::wstring> GetStringValue(...)`.

> but I'm not going to do it here.

Ok.

**Comment by GiovanniDicanio** [comment]
Using `std::optional` is an interesting alternative to the `bool` returning functions you initially suggested. But, also in this case, it seems to me that you loose the richer error information that an exception class can carry (like the last error code). 
I still think that leaving the current design as is is the best thing to do here. What I may do in the future is developing a different library, originated from this one, in a more ATL-friendly style, for example returning `HRESULT`s instead of throwing exceptions, for use in those code bases that aren't exception-friendly.

**Comment by WimLeflere** [comment]
An `std::variant<std::wstring,HRESULT>` could also be an option as return type. To pass both success and failure.

**Comment by GiovanniDicanio** [comment]
This library is designed with the _"throw exceptions on errors"_ philosophy in mind. Returning a `std::variant<std::wstring, HRESULT>` is a very different style. I don't believe that adding overloads that return `HRESULT`s or `std::variant<Type, HRESULT>` to the existing methods (and basically 2X-bloating the current public interface) would be a good thing for _this_ code base.

**Comment by GiovanniDicanio** [comment]
I reconsidered that, and thought of experimenting adding some _TryAction_ methods that return error codes instead of throwing on failure. They need testing, though.
