### ISSUE TITLE
Add system error string to RegException message

### ISSUE THREAD

**Issue by WimLeflere** [GiovanniDicanio/WinReg#3]
RegException stores the system error code.
It would be nice if this system error code was converted to a system error string and added to the exception message.

This can be done using [FormatMessage](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679351(v=vs.85).aspx).

**Comment by WimLeflere** [comment]
Possible implementation: https://github.com/WimLeflere/WinReg/tree/add-windows-system-error

**Comment by GiovanniDicanio** [comment]
The core piece of information is the system error code. I don't want to add complexity to my code to format it as a string (and should it be the localized string? Or the English error string?). The part of the client code that intercepts the exception can simply extract the error code, and if it needs that, it can format the error code to an error string using whatever language and specifications for `FormatMessage`. Note that the Unicode version of `FormatMessage` returns a wchar_t-string. You should convert to UTF-8 (adding other complexity) and then store a UTF-8 string in the exception class, to be returned with `what`.

**Comment by WimLeflere** [comment]
With system_error it is all done automatically: https://github.com/WimLeflere/WinReg/commit/a3d17bd

**Comment by GiovanniDicanio** [comment]
It seems to me in your code you invoked `FormatMessageA` to get a char-string; but it's not clear which code page it uses. In general, code pages are a source of bugs; it's better to operate with **Unicode UTF-16 at the Win32 API boundary**; then you can **convert to UTF-8 for cross-platform C++ code**. So, you should call `FormatMessageW` (or just `FormatMessage`, and do _Unicode builds_), get the UTF-16 error message, and then convert to UTF-8.

**Comment by WimLeflere** [comment]
I changed the implementation to no longer use FormatMessage but use system_error instead.

**Comment by GiovanniDicanio** [comment]
I spelunked inside` std::system_error` implementation and in VS2015 it seems they call `WideCharToMultiByte` using `CP_ACP` instead of `CP_UTF8` to convert the error string returned by `FormatMessageW`, so they convert from Unicode UTF-16 to some code page. Sounds sub-optimal to me. IMO, it's better to convert from UTF-16 to UTF-8 and store UTF-8-encoded text in `std::string`s.

**Comment by GiovanniDicanio** [comment]
I'm closing this issue and rejecting your code, since VS2015's `std::system_error` implementation uses some _"code page"_ for the error message string, and this leads to _subtle_ bugs (e.g. when writing error text to UTF-8-encoded log files). In my C++ code, I tend to use **UTF-8** in `char` strings, so I don't want this mismatch and _bug-prone_ `char` strings encoded with _"some code page"_.
