### ISSUE TITLE
Distribution question: winreg or winreg/winreg.hpp

### ISSUE THREAD

**Issue by wolfv** [GiovanniDicanio/WinReg#46]
Hi @GiovanniDicanio 

thanks for this useful library!
We're starting to distribute it in the conda-forge distribution. I am wondering if you'd prefer `include/WinReg.hpp` or `include/WinReg/WinReg.hpp` (with an additional `WinReg` folder)?

cc https://github.com/conda-forge/staged-recipes/pull/17128#issuecomment-983366677

**Comment by GiovanniDicanio** [comment]
Thanks @wolfv. Since this is currently a header-only library made by a _single_ header file, I would think that `include/WinReg.hpp` works fine. On the other hand, `include/WinReg/WinReg.hpp` would scale up better in case in the future more header files would be added to the library.

Feel free to pick what works best for you and your clients.

**Comment by wolfv** [comment]
Thanks. For now we do it without additional folder :)
