### ISSUE TITLE
How to query whether a certain item exists

### ISSUE THREAD

**Issue by SnowMeteors** [GiovanniDicanio/WinReg#66]
example `HKEY_CURRENT_USER\SOFTWARE\Classes\ms`
Can there be an API exists that returns true

**Comment by GiovanniDicanio** [comment]
Using `std::wstring_view` instead of `const std::wstring&` in that context would be really bad and a source of lots of bugs. In fact, typically Win32 C-style APIs (or at least those used in my code), expect **PCWSTR** as (Unicode UTF-16) **input string parameters**. [`PCWSTR` is a `_Null_terminated_ const wchar_t*`](https://giodicanio.com/2024/02/19/decoding-windows-sdk-types-pcwstr/); on the other hand, `std::wstring_view`s are **not guaranteed** to be **null terminated**! So using them as you suggest would cause lots of (subtle) bugs. Things might be different if the C++ standard library would provide a proper **null-terminated** version of string views.
