### ISSUE TITLE
Better to use std::string_view instead of const std::wstring& in parameters

### ISSUE THREAD

**Issue by UMU618** [GiovanniDicanio/WinReg#67]
Since the project is using C++17, then it's better to use `std::string_view` instead of `const std::wstring&` in parameters.

**Comment by GiovanniDicanio** [comment]
Of course, that is wrong. :-)

Since the proiect is using C++17, it is NOT (automatically) better to use
wstring_view instead of wstring const&.
These two options are DIFFERENT.

In particular, wstring const& guarantees efficient string passing + NUL
termination.
wstring_view does NOT guarantee NUL termination. And I need NUL-terminated
strings to be passed to Win32 C-interface APIs :)

Considering how many “suggestions” like this I’m receiving, I may consider
switching the project back to C++14 ;-) so the flood of string view
“improvements” suggestions will stop ;)

Bonus readings:

The Case of string_view and the Magic String:
https://giodicanio.com/2023/05/09/string_view-bug-the-case-of-string_view-and-the-magic-string/

https://giodicanio.com/2024/05/14/why-dont-you-use-string-views-like-std-wstring_view-instead-of-passing-std-wstring-by-const-reference/



Il giorno sab 3 ago 2024 alle 18:04 UMU ***@***.***> ha
scritto:

**Comment by UMU618** [comment]
Indeed, wstring_view does NOT guarantee NUL termination.

But if passing a `const wchar_t*`, it won't construct a `wstring`, and you can check the NUL termination when it is passed to Win32 C-interface APIs by the following codes:

```cpp
#include <iostream>
#include <string_view>

using namespace std::string_literals;
using namespace std::string_view_literals;

bool isNullTerminated(std::wstring_view s) noexcept {
  return !s.data()[s.size()];
}

int main() {
  std::cout << isNullTerminated(L"Hello World!") << '\n';
  std::cout << isNullTerminated(L"Hello World!"sv) << '\n';
  std::cout << isNullTerminated(L"Hello World!"s) << '\n';
  std::cout << isNullTerminated(L"Hello World!"sv.substr(0, 2)) << '\n';
}
```

**Comment by UMU618** [comment]
```cpp
bool isNullTerminated(std::wstring_view s) noexcept {
  if (wcsnlen(s.data(), s.size()) < s.size()) {
    return true;
  }
  return !s.data()[s.size()];
}
```

**Comment by GiovanniDicanio** [comment]
I don't like this approach. This would introduce inefficiencies as I have to check *every* string view for null termination before passing it to Win32 APIs, and throw exceptions in release builds when string views are not null terminated.
(Moreover, I'm not even sure if checking the the character immediately past the end of a string view is undefined behavior or not.)
Moreover, clients would experience various exceptions at runtime and blame this library as "unstable", while the problem is that they pass string views that are not null terminated.

The real solution to that problem would be the C++ standard library to introduce a _null-terminated_ string view. Until then, I'll leave the library interface as is.
