### ISSUE TITLE
Errors when compiling with Multi-Byte Character Set

### ISSUE THREAD

**Issue by mersadk** [GiovanniDicanio/WinReg#9]
I have a legacy project that uses Multi-Byte character set instead of Unicode. When I try to compile project containing winreg.hpp I get 163 errors with following message:

> cannot convert argument 3 from 'const wchar_t *' to 'LPCSTR'

Is there an easy way to fix this?

**Comment by GiovanniDicanio** [comment]
I don't have interest in supporting MBCS in 2018 (and complicating my code for that purpose). If you want to support both Unicode and MBCS, you can modify my code and adopt the TCHAR model. That would mean using TCHAR instead of wchar_t, replacing std::wstring with a std::basic_string<TCHAR>, etc.

**Comment by GiovanniDicanio** [comment]
@mersadk: I'm glad you were able to modify my code and adapt it to your MBCS needs. I don't feel I want to merge this TCHAR-based code in this repository, as my preference for today's code is to use **Unicode** instead of MBCS. I tend to reserve `std::string` for pure ASCII or UTF-8 (note that ASCII is a proper subset of UTF-8, so this works fine). I feel that those MBCS code bases become _"bug factories"_ when some portions of code assume a given `std::string` object contains text in code page X, but then you pass it to another section of code that assumes code page Y. It's a dangerous design, while trying to keep the whole code base Unicode, and immediately convert from a given code page to Unicode, feels much safer and higher-quality to me. These days I highly recommend moving legacy MBCS code bases to Unicode: I believe this is a very good and wise investment in code quality.

**Comment by mersadk** [comment]
@GiovanniDicanio Thank you for info.

**Comment by GiovanniDicanio** [comment]
@mersadk I'm glad of being of some help. Thank you for your interest in this repository.
